package dev.pi.postbox.protocol

/** Generated by scripts/generate-android-protocol-contract.mjs. Do not edit. */
object GeneratedPostboxProtocolContract {
    const val SUPPORTED_PROTOCOL_VERSION: String = "0.1.10"
    const val CONTRACT_FINGERPRINT: String = "714b443f32821ea63c645ea241207a87dbfeaf1e261639305f0f50b70b8109c6"
    val SEMANTIC_STATES: List<String> = listOf("working", "blocked", "waiting_for_postbox", "idle", "unknown")
    val PRESENCE_STATES: List<String> = listOf("live", "stale", "offline")
    val ASK_MODES: List<String> = listOf("single", "multi")
    val ASK_STATUSES: List<String> = listOf("pending", "answered", "cancelled", "expired", "superseded")
    val ASK_RESULT_STATUSES: List<String> = listOf("answered", "cancelled", "expired", "unavailable")
    val ASK_OPTION_PROVENANCES: List<String> = listOf("chat")
    val QUESTION_CHAT_STATES: List<String> = listOf("ready", "generating", "stopping", "stopped", "interrupted")
    val QUESTION_CHAT_AVAILABILITY_CODES: List<String> = listOf("request_missing", "request_not_pending", "extension_offline", "source_path_missing", "source_leaf_missing", "wrong_owner", "command_timeout", "runtime_failure", "chat_not_started", "invalid_command", "duplicate_command", "runtime_busy", "forbidden_origin", "rate_limited")
    val QUESTION_CHAT_ASSISTANT_STATUSES: List<String> = listOf("streaming", "final", "stopped", "interrupted")
    val QUESTION_CHAT_TOOL_STATES: List<String> = listOf("running", "success", "error", "stale")
    val QUESTION_CHAT_TOOL_NAMES: List<String> = listOf("repository_read", "repository_grep", "repository_find", "repository_list", "propose_answer")
    val QUESTION_CHAT_EVENT_TYPES: List<String> = listOf("lifecycle", "message.started", "assistant.text.delta", "message.finished", "tool.started", "tool.finished", "transport")
    val QUESTION_CHAT_MODEL_SOURCES: List<String> = listOf("originating", "pi-default")
    val QUESTION_CHAT_SEND_MODES: List<String> = listOf("turn", "steer")
    val FCM_TYPES: List<String> = listOf("ask.created", "ask.resolved")
}
